name: shared
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  list_news:
    path: ../../features/list_news

  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
